#!/bin/bash
cfssl gencert -initca ca/ca-csr.json | cfssljson -bare ca
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca/ca-config.json -profile=default ca/consul-csr.json | cfssljson -bare consul
GOSSIP_ENCRYPTION_KEY=$(consul keygen)
kubectl create secret generic consul --from-literal="gossip-encryption-key=${GOSSIP_ENCRYPTION_KEY}" --from-file=ca.pem --from-file=consul.pem --from-file=consul-key.pem
kubectl create configmap consul --from-file=configs/server.json
kubectl get configmap
kubectl create -f persistentvolumes/data-consul-0-pv.yaml
kubectl create -f persistentvolumes/data-consul-0-pvc.yaml
#kubectl create -f persistentvolumes/data-consul-1-pv.yaml
#kubectl create -f persistentvolumes/data-consul-1-pvc.yaml
#kubectl create -f persistentvolumes/data-consul-2-pv.yaml
#kubectl create -f persistentvolumes/data-consul-2-pvc.yaml
kubectl create -f services/consul.yaml
kubectl create -f statefulsets/consul.yaml
kubectl get pods -w

